module.exports = [
    {
        short_name: 'Study Hall',
        api_id: '148030000000002677',
        period: 2,
        instructor_title: '',
        instructor_first_name: 'Megan',
        instructor_last_name: 'Ahern',
        day_color: 'blue',
        office_hours: '',
        office_hours_zoom_link: '',
        class_zoom_link: 'https://zoom.us/j/4398761768?pwd=QnBIZEdYUDVaTFRLUUNZZ2F1QUZyUT09',
        instructor_email: 'megan.ahern@stemk12.org',
        has_assignments: false,
        assignmentGroups: [],
    },
    {
        short_name: 'Biology',
        instructor_title: '',
        instructor_first_name: 'Kent',
        instructor_last_name: 'Schnacke',
        api_id: '148030000000001728',
        period: 4,
        day_color: 'blue',
        office_hours: 'Wed, 3-3:45, or by appt',
        office_hours_zoom_link: 'https://zoom.us/j/93841467014?pwd=WmE2Z3E4Nzc2TzMzV1hqOGpjVmQ3Zz09',
        class_zoom_link: 'https://zoom.us/j/91597734260',
        instructor_email: 'kent.schnacke@stemk12.org',
        has_assignments: true,
        assignmentGroups: [
            {
                id: '148030000000004483',
                name: 'General Course Work',
                authorized: false,
            }, {
                id: '148030000000004484',
                name: 'Demonstrating Knowledge',
                authorized: false,
            }
        ],
    },
    {
        short_name: 'Creative Writing',
        instructor_title: '',
        instructor_first_name: 'Jon',
        instructor_last_name: 'Jennings',
        api_id: '148030000000001808',
        period: 6,
        day_color: 'blue',
        office_hours: 'Wed, 3-4',
        office_hours_zoom_link: 'https://zoom.us/j/99270348006?pwd=cXlhSmJrTWoxUDRMaEs0RzRzT0ZWQT09',
        class_zoom_link: 'https://zoom.us/j/94399073841?pwd=VEI2ZlpuZnVtV3FmZ2s2Y2gwVkgvZz09',
        instructor_email: 'jon.jennings@stemk12.org',
        has_assignments: true,
        assignmentGroups: [
            {
                id: '148030000000004370',
                name: 'Course Work (Classwork, Homework, Responses, Timed Writing)',
                authorized: true,
            }, {
                id: '148030000000004484',
                name: 'Demonstrating Knowledge',
                authorized: true,
            }
        ],
    },
    {
        short_name: 'Algebra I',
        instructor_title: '',
        instructor_first_name: 'Lore',
        instructor_last_name: 'Stidham',
        api_id: '148030000000002394',
        period: 8,
        day_color: 'blue',
        office_hours: 'Tues, 3-3:30',
        office_hours_zoom_link: 'https://zoom.us/j/94156308133?pwd=dDZGaVRCbFl5UnlsRkdQK3dXeFpUZz09',
        class_zoom_link: 'https://zoom.us/j/97293867827?pwd=S2x4NWV4Nko0V2Qybk5NYzRsQjRoQT09',
        instructor_email: 'lori.stidham@stemk12.org',
        has_assignments: true,
        assignmentGroups: [
            {
                id: '148030000000007153',
                name: 'Coursework',
                authorized: true,
            }, {
                id: '148030000000007154',
                name: 'Class Participation',
                authorized: true,
            }, {
                id: '148030000000007155',
                name: 'Final Demonstration of Knowledge',
                authorized: false,
            }
        ],
    },
    {
        short_name: 'Spanish I',
        instructor_title: 'Senora',
        instructor_first_name: 'Kayla',
        instructor_last_name: 'Sandoval',
        api_id: '148030000000001807',
        period: 3,
        day_color: 'gold',
        office_hours: 'Tues, 2:55-3:30',
        office_hours_zoom_link: 'https://zoom.us/j/91217469681?pwd=RVRuSWE1Nmx5Mm1scUZyR3Jpazl2Zz09',
        class_zoom_link: 'https://zoom.us/j/91217469681?pwd=RVRuSWE1Nmx5Mm1scUZyR3Jpazl2Zz09',
        instructor_email: 'kayla.sandoval@stemk12.org',
        has_assignments: true,
        assignmentGroups: [
            {
                id: '148030000000006379',
                name: 'Classwork',
                authorized: true,
            },
        ],
    },
    {
        short_name: 'English I',
        instructor_title: 'Dr.',
        instructor_first_name: 'Aaron',
        instructor_last_name: 'Guggenheim',
        api_id: '148030000000001910',
        period: 5,
        day_color: 'gold',
        office_hours: 'Th/Fri, 2:55-3:45',
        office_hours_zoom_link: 'https://zoom.us/j/4792417755',
        class_zoom_link: 'https://zoom.us/j/97651383424?pwd=RmJaNG9ieW9pODJJUm10Lzd1NGpoZz09',
        instructor_email: 'aaron.guggenheim@stemk12.org',
        has_assignments: true,
        assignmentGroups: [
            {
                id: '148030000000003694',
                name: 'Coursework',
                authorized: true,
            },
            {
                id: '148030000000007054',
                name: 'Performance Assessments',
                authorized: true,
            },
            {
                id: '148030000000007055',
                name: 'Formative Assessments',
                authorized: true,
            },
            {
                id: '148030000000007056',
                name: 'Summative Assessments',
                authorized: true,
            },
        ],
    },
    {
        short_name: 'Psychology',
        instructor_title: '',
        instructor_first_name: 'Shonda',
        instructor_last_name: 'Kaspar',
        api_id: '148030000000002012',
        period: 7,
        day_color: 'gold',
        office_hours: 'By appt only',
        office_hours_zoom_link: 'https://zoom.us/j/93780761318',
        class_zoom_link: 'https://zoom.us/j/93780761318',
        instructor_email: 'shonda.kaspar@stemk12.org',
        has_assignments: true,
        assignmentGroups: [
            {
                id: '148030000000006396',
                name: 'Coursework',
                authorized: true,
            },
        ],
    },
    {
        short_name: 'Geography',
        instructor_title: '',
        instructor_first_name: 'Kyle',
        instructor_last_name: 'Perret',
        api_id: '148030000000001811',
        period: 9,
        day_color: 'gold',
        office_hours: 'Tu/Th, 3-3:40',
        office_hours_zoom_link: 'https://zoom.us/j/96112146737?pwd=aEJYR3VraGdMRGYzQzI4T2N5ZzN2dz09',
        class_zoom_link: 'https://zoom.us/j/96112146737?pwd=aEJYR3VraGdMRGYzQzI4T2N5ZzN2dz09',
        instructor_email: 'kyle.perret@stemk12.org',
        has_assignments: true,
        assignmentGroups: [
            {
                id: '148030000000004435',
                name: 'Assignments',
                authorized: true,
            },
            {
                id: '148030000000007046',
                name: 'Course work',
                authorized: false,
            },
            {
                id: '148030000000007114',
                name: 'Demonstrating Knowledge ',
                authorized: false,
            },
            {
                id: '148030000000007116',
                name: 'Daily Grade ',
                authorized: true,
            },
        ],
    },
]

// module.exports = [
//     {
//         name: 'Biology - STEMHS039S1 - Schnacke',
//         id: '148030000000001675',
//         period: 2,
//         day_color: 'blue',
//     },
//     {
//         name: 'Game Design I',
//         id: '148030000000002385',
//         period: 4,
//         day_color: 'blue',
//     },
//     {
//         name: 'English I - Period 6',
//         id: '148030000000001859',
//         period: 6,
//         day_color: 'blue',
//     },
//     {
//         name: 'Spanish I - STEMHS069SS1 - Sandoval - Period 8',
//         id: '148030000000001803',
//         period: 8,
//         day_color: 'blue',
//     },
//     {
//         name: 'HS Algebra I - Fall 2020',
//         id: '148030000000002385',
//         period: 3,
//         day_color: 'gold',
//     },
//     {
//         name: 'HS Study Hall S1',
//         id: '148030000000002683',
//         period: 5,
//         day_color: 'gold',
//     },
//     {
//         name: 'Digital Photograph I',
//         id: '148030000000002385',
//         period: 7,
//         day_color: 'gold',
//     },
//     {
//         name: 'United States Government',
//         id: '148030000000002042',
//         period: 9,
//         day_color: 'gold',
//     },
// ]

// module.exports = [
//     {
//         name: 'Study Hall',
//         id: '',
//         period: 2,
//         instructorLastName: 'Ahem',
//         instructorFirstName: 'Megan',
//         day_color: 'blue',
//         classStart: '7:50am',
//         classEnd: '9:29am',
//     },
//     {
//         name: 'Biology',
//         id: '',
//         period: 4,
//         instructorLastName: 'Schnacke',
//         instructorFirstName: 'Kent',
//         day_color: 'blue',
//         classStart: '9:34am',
//         classEnd: '11:06am',
//     },
//     {
//         name: 'Intro to Creative Writing',
//         id: '',
//         period: 6,
//         instructorLastName: 'Jennings',
//         instructorFirstName: 'Jonathan',
//         day_color: 'blue',
//         classStart: '11:11am',
//         classEnd: '1:15pm',
//     },
//     {
//         name: 'Algebra I',
//         id: '',
//         period: 8,
//         instructorLastName: 'Stidham',
//         instructorFirstName: 'Lori',
//         day_color: 'blue',
//         classStart: '1:20pm',
//         classEnd: '2:55pm',
//     },
//     {
//         name: 'Spanish I',
//         id: '',
//         period: 3,
//         instructorLastName: 'Schlomer',
//         instructorFirstName: 'Kayla Marie',
//         day_color: 'gold',
//         classStart: '7:50am',
//         classEnd: '9:29am',
//     },
//     {
//         name: 'English I',
//         id: '',
//         period: 5,
//         instructorLastName: 'Aaron Micah',
//         instructorFirstName: 'Guggenheim',
//         day_color: 'gold',
//         classStart: '9:34am',
//         classEnd: '11:06am',
//     },
//     {
//         name: 'Psychology',
//         id: '',
//         period: 7,
//         instructorLastName: 'Kaspar',
//         instructorFirstName: 'Shonda',
//         day_color: 'gold',
//         classStart: '11:11am',
//         classEnd: '1:15pm',
//     },
//     {
//         name: 'Geography',
//         id: '',
//         period: 9,
//         instructorLastName: 'Perret',
//         instructorFirstName: 'Kyle',
//         day_color: 'gold',
//         classStart: '1:20pm',
//         classEnd: '2:55pm',
//     },
//     {
//         name: 'Advisement',
//         id: '',
//         period: 0,
//         instructorLastName: 'Moreno',
//         instructorFirstName: 'Maria Del Rosario',
//         day_color: 'blue/gold',
//         classStart: '10:40am',
//         classEnd: '11:25am',
//     },
// ]